version: '3.8'

services:
  # MongoDB for Favorites Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Redis for Favorites Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your-secret-key-for-development-only
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  # Catalog Service
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/catalog-service
      - PORT=3002
    depends_on:
      - mongodb
      - auth-service
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order-service
      - PORT=3003
    depends_on:
      - mongodb
      - auth-service
      - catalog-service
    networks:
      - ecommerce-network

  # Admin Dashboard Service
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    depends_on:
      - auth-service
      - catalog-service
      - order-service
    networks:
      - ecommerce-network

  # Favorites Service
  favorites-service:
    build:
      context: ./app/favorites
      dockerfile: Dockerfile
    container_name: favorites-service
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/favorites-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PORT=3005
    depends_on:
      - mongodb
      - redis
      - auth-service
    networks:
      - ecommerce-network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - CATALOG_SERVICE_URL=http://catalog-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - ADMIN_SERVICE_URL=http://admin-service:3004
      - FAVORITES_SERVICE_URL=http://favorites-service:3005
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - admin-service
      - favorites-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data:
