version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  # Favorites Service
  favorites-service:
    build:
      context: ./app/favorites
      dockerfile: Dockerfile
    container_name: favorites-service
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/favorites-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3005
    depends_on:
      - mongodb
      - redis
    networks:
      - ecommerce-network

  # Simple Frontend (Static HTML)
  simple-frontend:
    image: nginx:alpine
    container_name: simple-frontend
    ports:
      - "3000:80"
    volumes:
      - ./simple-frontend:/usr/share/nginx/html
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data:
